### PR TITLE
fix tool miscategorization

### PR DESCRIPTION
**Pull request by zhimin-z**
ggml, as a prevalent serialization format, is better put under `model serialization` rather than the inference section. though I admit this is better falling under multiple labels...

### CODE REVIEW

**Comment by zhimin-z** [comment]
relocate ludwig from data pipeline onto serving, also, the description of ludwig is wrong, you can verify it thru its documentation.

**Comment by axsaucedo** [comment]
Thanks @zhimin-z - ludwig indeed continues to have its USP in being a declarative ML framework for pipelines, but indeed seems they changed their description to update the word LLM - happy to update so it matches the repo. In regards to change of section, ludwig is not a serving platform, it continues to focus more on the experimentation side (i.e. productionisation just uses Ray / pushes to huggingface)

**Comment by axsaucedo** [comment]
Btw seems quite a lot of commits that are separate to the PR, may need to rebase?

**Comment by axsaucedo** [comment]
@zhimin-z do you know what is this `pull` tool? Seems it's force pushed some strange content, let's avoid merging any strange content from random bots

**Comment by zhimin-z** [comment]
> @zhimin-z do you know what is this `pull` tool? Seems it's force pushed some strange content, let's avoid merging any strange content from random bots

No worry, I set up a bot to pull from the upstream branch for syncing. Yeah, Ludwig is a training tool, that's the reason why I relocate it.

**Comment by axsaucedo** [comment]
Ok I see, I would be keen to disable bots, unless we host the code under EthicalML, as there's been quite a lot of situations where supply chain vulnerabilities arise from bots, etc (i.e. injecting cryptomining code, or taking credentials, etc) - it seems to me like keeping branches in sync is probably a slight overhead, but the risk is not worth the convenience

**Pull request merged**
