### PR TITLE
Add MLEM and Iterative Studio 🌟

### PR DESCRIPTION
**Pull request by mertbozkir**
MLEM helps you package and deploy machine learning models. It saves ML models in a standard format that can be used in a variety of production scenarios, such as real-time REST serving or batch processing.

Iterative Studio, combining the power of leading open-source tools.

- [X] I added MLEM tool into Model Serving and Monitoring section.
- [X] Also, I added Iterative Studio into Commercial Platforms section.

Best Regards...

### CODE REVIEW

**Comment by axsaucedo** [comment]
@mertbozkir thanks for the contribution - please read the CONTRIBUTING.md file, as entries need to be in alphabetical order, with github links where possible

**Comment by axsaucedo** [comment]
@mertbozkir will you  be able to update?

**Comment by mertbozkir** [comment]
Hello @axsaucedo, I didn't get notifications I'm on it right now.  😎

**Comment by mertbozkir** [comment]
@axsaucedo I changed the order of the iterative studio and MLEM. 🙂

**Comment by axsaucedo** [comment]
Great thank you @mertbozkir

**Comment by mertbozkir** [comment]
My pleasure! @axsaucedo 🤗

**Pull request merged**
