### PR TITLE
add distributed training tools

### PR DESCRIPTION
**Pull request by zhimin-z**
add H2O

### CODE REVIEW

**Comment by axsaucedo** [comment]
H2O is already in the list (a few times) so closing - unless proposal is to change ot another section

**Comment by zhimin-z** [comment]
> H2O is already in the list (a few times) so closing - unless proposal is to change ot another section

Hi @axsaucedo I do not think they are similar. [H2O Driverless AI](https://www.h2o.ai/products/h2o-driverless-ai/) cannot represent the main products of [H2O](https://github.com/h2oai/h2o-3), if we need to leave one, then we probably should keep [H2O](https://github.com/h2oai/h2o-3) rather than the former

**Comment by axsaucedo** [comment]
H2O is already present in computation optimization section

**Comment by zhimin-z** [comment]
> H2O is already present in computation optimization section

Since Ploomber appears twice in our list (https://github.com/EthicalML/awesome-production-machine-learning/pull/355), I think we can do the same things for other tools, why not H2O? @axsaucedo

**Comment by zhimin-z** [comment]
> H2O is already present in computation optimization section

Any update? @axsaucedo

**Comment by zhimin-z** [comment]
> > H2O is already present in computation optimization section
> 
> I think including a tool twice might be meaningful in this case. The most representative tool of H2O is https://github.com/h2oai/h2o-3 rather than https://www.h2o.ai/products/h2o-driverless-ai/. Maybe we can replace the latter with the former? I can make a pr then.
> 
> Also, since Ploomber appears twice in our list (#355 and #208), I think we can do the same things for other tools, why not H2O? @axsaucedo

> H2O is already present in computation optimization section

Any update? @axsaucedo

**Comment by zhimin-z** [comment]
> > H2O is already present in computation optimization section
> 
> I think including a tool twice might be meaningful in this case. The most representative tool of H2O is https://github.com/h2oai/h2o-3 rather than https://www.h2o.ai/products/h2o-driverless-ai/. Maybe we can replace the latter with the former? I can make a pr then.
> 
> Also, since Ploomber and Alibi-Detect appear twice in our list (#355 and #208)
> 
> image image
> 
> Overall, I think we can do the same things for other tools, why not H2O? @axsaucedo

Any update? @axsaucedo

**Comment by zhimin-z** [comment]
> Reference

Any update? @axsaucedo

**Pull request closed without merging**
