### PR TITLE
create model compression tools

### PR DESCRIPTION
**Pull request by zhimin-z**
This module aims to add compression tools specifically designed for machine learning models.
Is it good to ship? @axsaucedo

### CODE REVIEW

**Comment by zhimin-z** [comment]
Is it good to ship? @axsaucedo

**Review by axsaucedo — CHANGES_REQUESTED** [review]
Thanks for adding @zhimin-z, I have certainly seen a rise of model optimization, compilation and compression libraries (also closed source like https://www.modular.com/max/mojo) which I agree would be relevant to have in a new section, as the "optimized computation" would not encompass these tools - my suggestion would be to extent the title to something more broad such as "model optimization, compilation and compression" - other than that look good

**Comment by zhimin-z** [comment]
> Thanks for adding @zhimin-z, I have certainly seen a rise of model optimization, compilation and compression libraries (also closed source like https://www.modular.com/max/mojo) which I agree would be relevant to have in a new section, as the "optimized computation" would not encompass these tools - my suggestion would be to extent the title to something more broad such as "model optimization, compilation and compression" - other than that look good

Fixed!

**Review by axsaucedo — APPROVED** [review]
LGTM

**Pull request merged**
