### PR TITLE
Add two libraries for drift detection

### PR DESCRIPTION
**Pull request by NastasiaSaby**
Add Alibi-detect and evidently

### CODE REVIEW

**Comment by igorbrigadir** [comment]
I don't think it warrants a separate section, https://github.com/SeldonIO/alibi-detect should be under "Outlier and Anomaly Detection", and https://github.com/evidentlyai/evidently should be under "Model Serving and Monitoring"

**Comment by axsaucedo** [comment]
Thank you for your contribution @NastasiaSaby - as @igorbrigadir pointed out, these would be better fit on the anomaly & outlier detection. Would you be able to do the update?

**Comment by NastasiaSaby** [comment]
I get your point. I'll do that and will update you as soon as it is done.

**Comment by axsaucedo** [comment]
Great, thanks!

**Comment by NastasiaSaby** [comment]
@axsaucedo @igorbrigadir I did the modification.

**Comment by axsaucedo** [comment]
Thank you @NastasiaSaby - it's almost good to go. All the entries are in alphabetical order relative to the section, and entries have the sticker with stars (the img link next to the title) if you can update these two points we should be able to merge. Thank you!

**Comment by NastasiaSaby** [comment]
@axsaucedo done :).

**Comment by axsaucedo** [comment]
Great! Thank you for your contribution @NastasiaSaby !

**Pull request merged**
