### PR TITLE
Add online experimentation section

### PR DESCRIPTION
**Pull request by hardianlawi**

### CODE REVIEW

**Comment by hardianlawi** [comment]
I added another project from Gojek called Merlin to the model serving section.

**Comment by axsaucedo** [comment]
Intereting proposal - in order to open a new section there needs to be more than two projects, and it seems that Turing is too small / recent to be added to the list. For now it could still be worth adding "planout" into the ""Model Training Orchestration" section tho.

**Comment by hardianlawi** [comment]
Got it. I have removed the small projects I added and moved planout to ""Model Training Orchestration"" as suggested.

**Comment by axsaucedo** [comment]
Great - thank you @hardianlawi, one more request, the libraries have to be in alphabetical order, other than that it should be good to merge

**Comment by hardianlawi** [comment]
Fixed @axsaucedo

**Comment by axsaucedo** [comment]
Nice one - thank you @hardianlawi

**Pull request merged**
