### PR TITLE
Adds Hamilton UI to metadata

### PR DESCRIPTION
**Pull request by skrawcz**
Hamilton now comes with an open source metadata UI that captures lineage, provenance, has observability, and provides a catalog view.

### CODE REVIEW

**Comment by zhimin-z** [comment]
Hi, thanks for contributing. Do you check `Data Pipeline` section yet? We suggest not including the same tool twice. There is already a Hamilton tool in that section.

**Comment by skrawcz** [comment]
@zhimin-z the package is different (sf-hamilton-ui vs sf-hamilton), but lives in the same repository. What do you suggest?

**Comment by zhimin-z** [comment]
> @zhimin-z the package is different (sf-hamilton-ui vs sf-hamilton), but lives in the same repository. What do you suggest?

Why not refine `sf-hamilton` and say something about its UI. You know, a pure interface is hard to highlight as a separate tool for this list.

**Comment by skrawcz** [comment]
Well it's not just a UI (catalog, lineage, observability, execution telemetry), but sure I can add to the existing one - thanks.

**Pull request closed without merging**
