### PR TITLE
Add benchmarking and best practices platform

### PR DESCRIPTION
**Pull request by zhimin-z**

### CODE REVIEW

**Comment by axsaucedo** [comment]
We've had a discussion in the past a while back on whether we would add non-software based orgs, I believe this may be better for our other list https://github.com/EthicalML/awesome-artificial-intelligence-guidelines - closing but we can add there

**Comment by zhimin-z** [comment]
> We've had a discussion in the past a while back on whether we would add non-software based orgs, I believe this may be better for our other list https://github.com/EthicalML/awesome-artificial-intelligence-guidelines - closing but we can add there

Is there a place for my pr? I fail to fill it in.

**Comment by axsaucedo** [comment]
I believe we could look at adding a new section, but given its not a production framework it would be hard to add on this list

**Comment by zhimin-z** [comment]
> I believe we could look at adding a new section, but given its not a production framework it would be hard to add on this list

Does the production machine learning list have to be software? But I have seen there are many benchmarks in the list already.



Neither of them are meeting the standards regarding non-software-based orgs. @axsaucedo

**Comment by zhimin-z** [comment]
> I believe we could look at adding a new section, but given its not a production framework it would be hard to add on this list

Would you mind reopening this pr for a future discussion?

**Comment by zhimin-z** [comment]
And tools like [Metaworld](https://github.com/Farama-Foundation/Metaworld)?

**Comment by zhimin-z** [comment]
> I believe we could look at adding a new section, but given its not a production framework it would be hard to add on this list

Hi @axsaucedo Would you mind reopening this in case for further discussion? Appreciated a lot!

**Pull request closed without merging**
