### PR TITLE
adding Outlier and Anomaly Detection section

### PR DESCRIPTION
**Pull request by visenger**
related to the issue #99

### CODE REVIEW

**Comment by axsaucedo** [comment]
Looks great @visenger ! Would you be able to add it on the "index / table" at the very top? Other than that looks good to merge!

**Comment by visenger** [comment]
@axsaucedo yepp! there is a second commit with TOC.

**Comment by axsaucedo** [comment]
THanks! Although @visenger seems like it may need to go on the next row, if you have a look at the generated markdown table the feature engineering cell is removed as the table is only 3 columns. If you add it as the first column on the last row  (before feature stores) that should fix it

**Comment by visenger** [comment]
@axsaucedo ahh! Now should be ok.

**Pull request merged**
