### PR TITLE
add netron

### PR DESCRIPTION
**Pull request by fkromer**

### CODE REVIEW

**Comment by axsaucedo** [comment]
Awesome find @fkromer ! Thanks for the contribution :) the entries are now in alphabetical order, if you sort it accordingly i can merge

**Comment by fkromer** [comment]
@axsaucedo Should be fixed now :smirk:

**Comment by axsaucedo** [comment]
Nice!

**Comment by axsaucedo** [comment]
Thanks @fkromer for the contribution

**Pull request merged**
