### PR TITLE
Adding Dolt

### PR DESCRIPTION
**Pull request by ssakhavi**
Dolt is a SQL database that you can fork, clone, branch, merge, push and pull just like a git repository. Connect to Dolt just like any MySQL database to run queries or update the data using SQL commands. Use the command line interface to import CSV files, commit your changes, push them to a remote, or merge your teammate's changes.

### CODE REVIEW

**Review by axsaucedo — CHANGES_REQUESTED** [review]
Cool - great addition - can you add it alphabetically and then i can merge

**Comment by axsaucedo** [comment]
Following up will you get a chance to update?

**Comment by ssakhavi** [comment]
@axsaucedo I changed it. Please take a look.

**Comment by axsaucedo** [comment]
Thank you @ssakhavi - it seems you are still missing the star badge, once you add that we should be able to merge it

**Comment by ssakhavi** [comment]
@axsaucedo added the stars

**Comment by axsaucedo** [comment]
Great - thank you very much @ssakhavi

**Pull request merged**
