### PR TITLE
add commercial tools

### PR DESCRIPTION
**Pull request by zhimin-z**
add Numenta

### CODE REVIEW

**Comment by axsaucedo** [comment]
This doesn't seem to have any platform / offerings and seems more of a consulting firm from case studies

**Comment by zhimin-z** [comment]
> This doesn't seem to have any platform / offerings and seems more of a consulting firm from case studies

Hi, @axsaucedo That is not true. Take a look at their product: https://twitter.com/Numenta

**Comment by igorbrigadir** [comment]
I really think it's worth reconsidering this - but Adding https://github.com/numenta/NAB under Outlier and Anomaly Detection or under Industry Strength Benchmarking and Evaluation where it's more appropriate

**Comment by zhimin-z** [comment]
> I really think it's worth reconsidering this - but Adding https://github.com/numenta/NAB under Outlier and Anomaly Detection or under Industry Strength Benchmarking and Evaluation where it's more appropriate

Thanks for suggestion. But that brought the old issue to the water. When the company both releases open-source tools and provide commercial platforms together, shall we add it to open-souce section or commercial sections? Currently the categorization rinciples are chaotic in the list. For example, WandB is open-source tool but still put it under commercial section. HuggingFace is a company for profit either but we do not put it under the commercial list.

I still think we need to set up a more clear standard to decide which tools should fall into which category, or eventually this list becomes too chaotic to maintain in the future. @axsaucedo

**Comment by axsaucedo** [comment]
> Take a look at their product: https://twitter.com/Numenta.
This is only a link to their twitter - their website only has a link to a private beta, so I don't see this addressing the point on the commercial section.

> I really think it's worth reconsidering this - but Adding https://github.com/numenta/NAB under Outlier and Anomaly Detection or under Industry Strength Benchmarking and Evaluation where it's more appropriate

Ok this is actually quite interesting, yes I would be keen to add https://github.com/numenta/NAB to the benchmarking section.

**Pull request closed without merging**
