### PR TITLE
add a new tool for model serving and monitoring

### PR DESCRIPTION
**Pull request by tanersekmen**

### CODE REVIEW

**Comment by tanersekmen** [comment]
Hi, skops is a new framework that shares your scikit-learn based models and put them in production

**Comment by tanersekmen** [comment]
Hi @axsaucedo, can you check my pr?

**Review by axsaucedo — CHANGES_REQUESTED** [review]
@tanersekmen thank you for the contribution - we'd need to have these by alphabetical order, but looks good - if you address that and fix merge conflicts we can merge

**Review by tanersekmen — COMMENTED** [review]
added a new framework as told to me

**Comment by tanersekmen** [comment]
> @tanersekmen thank you for the contribution - we'd need to have these by alphabetical order, but looks good - if you address that and fix merge conflicts we can merge

Thanks for your feedback. I am happy to contribute.

**Pull request closed without merging**
