### PR TITLE
create-auto-pdf-release

### PR DESCRIPTION
**Pull request by zhimin-z**
refer to https://github.com/EthicalML/awesome-production-machine-learning/issues/353

### CODE REVIEW

**Comment by zhimin-z** [comment]
refer to https://github.com/EthicalML/awesome-production-machine-learning/issues/353

**Comment by axsaucedo** [comment]
This seems like a copy paste from the repo, did you run it? The logic doesn't reflect what is outlined in the PR as it doesn't create the release, best to run a few tests on your fork before opening the PR - it's a good start however, and you can trigger actions manually on the actions tab - let me know if you have any questions.

**Comment by axsaucedo** [comment]
@zhimin-z this seems like a copy paste, doesn't seem this PR really is ready to be open / run, let me know thoughts otherwise I'll close and we can discuss implementation in the issue before opening a PR

**Comment by zhimin-z** [comment]
> @zhimin-z once again I very much appreiate the contributions, but this seems like a copy paste, it doesn't seem this PR really is ready to be reviewed, let me know thoughts otherwise I'll close and we can discuss implementation in the issue before opening a PR

I have tested it for a while and it seems to work like great.
Here is the result preview:
image
image
image
image

@axsaucedo Would you like to take a check?

**Comment by axsaucedo** [comment]
Thank you for having a look @zhimin-z this is starting to look good - there are a couple more things and we should be good to merge:
* The idea would be to actually make a release, so it can be accessed and viewed through the repo
* Following from that, it would be able to run on a monthly basis so it's automated (as opposed to on merge)

THis would allow people that follow the repo to get an update of the latest changes (perhaps even through changelog)

Let me know thoughts - that will provide quite a good functionality for users

**Comment by zhimin-z** [comment]
> Thank you for having a look @zhimin-z this is starting to look good - there are a couple more things and we should be good to merge:
> 
> * The idea would be to actually make a release, so it can be accessed and viewed through the repo
> * Following from that, it would be able to run on a monthly basis so it's automated (as opposed to on merge)
> 
> THis would allow people that follow the repo to get an update of the latest changes (perhaps even through changelog)
> 
> Let me know thoughts - that will provide quite a good functionality for users

I made some changes accordingly. Would you like to try on this version, @axsaucedo?

**Comment by zhimin-z** [comment]
> Thank you for having a look @zhimin-z this is starting to look good - there are a couple more things and we should be good to merge:
> 
> * The idea would be to actually make a release, so it can be accessed and viewed through the repo
> * Following from that, it would be able to run on a monthly basis so it's automated (as opposed to on merge)
> 
> THis would allow people that follow the repo to get an update of the latest changes (perhaps even through changelog)
> 
> Let me know thoughts - that will provide quite a good functionality for users

I made some changes accordingly. Would you like to try on this version, @axsaucedo?

**Comment by axsaucedo** [comment]
This is looking good @zhimin-z - thank you very much for the effort, I can see the many commits to achieve this.

One thing I can see is that the release is named "monthly release", we could name it MM-YY so we have the releases of every month (if people are curious of the older versions).

Other than that it looks good - in order to merge I will fork the respective github actions and we can run them linking to the forks, that way it's more secure (I normally avoid having gh actions where possible directly from external repos as it's a security risk)

**Comment by zhimin-z** [comment]
> 
Thanks for your feedback. I do think there might not be necessary to make the date explicit since the date appears automatically over the release:
image

I am thinking about if we can only have an exclusive version of the release of the latest at all times. @axsaucedo

**Pull request closed without merging**
