### PR TITLE
Added BentoML framework to "Model Deployment and Orchestration Frameworks"

### PR DESCRIPTION
**Pull request by parano**
Hi - I'd like to add BentoML to the list of Model Deployment and Orchestration Frameworks. It's a framework agnostic serving system, that does dependency management, model management, and high-performance API serving.

I think it might make more sense to separate model serving frameworks such as BentoML, Clipper, MXNet Model Server, TF-serving and deployment orchestration frameworks such as Seldon, KFServing, Redis-AI, etc since people usually pick one serving framework and another deployment framework independently. Happy to make that contribution as well if I could get consensus from the community.

Cheers!

### CODE REVIEW

**Comment by axsaucedo** [comment]
Looks great @parano ! Can you append it instead of prepending? I've been meaning to convert all to alphabetical order but would be quite a feat so haven't gotten around to it, but for the meantime let's append it to the model orchestration

**Comment by parano** [comment]
Thanks, @axsaucedo! totally thought that list was already in alphabetical order ;)  updated!

**Comment by axsaucedo** [comment]
Thank you! I wish... soon it will be hopefully 😄

**Comment by parano** [comment]
Thanks @axsaucedo!

VIM has a built-in command `:sort` to sort selected lines alphabetically, happy to help out on that if needed!

**Comment by axsaucedo** [comment]
Oh that's very useful, does taht work on selection as well? Only inconvenience I see is that the lines are prefixed with "`* [" but I guess that could be removed to run that command

If you'd be able to do that, it would be awesome!

**Comment by parano** [comment]
@axsaucedo yes I think it works if all lines start with `* [`, I will give it a try!

**Pull request merged**
