### PR TITLE
add cnvrg CORE to open source platforms section

### PR DESCRIPTION
**Pull request by fkromer**

### CODE REVIEW

**Comment by axsaucedo** [comment]
Thank you @fkromer ! As per the discussion in your previous PR, let's put it on Model Orchestration for now, as "platform" is quite ambiguous and I don't think it would be worth creating an entire section just for one project

**Comment by fkromer** [comment]
I've moved cnvrg CORE into the "Model Deployment and Orchestration Frameworks" section. I don't think it fits into there really well because in comparison with other free versions of the commercial E2E platforms it offers way more than deployment and orchestration.

**Comment by axsaucedo** [comment]
I do agree with you @fkromer, the main reasons I push back for the other section is not because it doesn't make sense, but because 1) platforms is too broad, and 2) only having 2-3 projects would not be enough to start a new section - I do think it's often hard to categorize each as many actually do more than just one thing (i.e. Kubeflow, H2o, etc etc).

We have now re-ordered the list alphabetically (thanks to an awesome contribution) which will help massively in ordering the libraries fairly, however it seem this has caused merge conflicts with the PR, would you be able to address them? Happy to help with it as well in this PR if conflicts are too big

**Comment by axsaucedo** [comment]
Thanks!

**Pull request merged**
