### PR TITLE
Add open distro to the anomaly detection chapter

### PR DESCRIPTION
**Pull request by spoilerdo**
The Open Distro for Elasticsearch Anomaly Detection plugin enables you to leverage Machine Learning based algorithms to automatically detect anomalies as your log data is ingested. Combined with Alerting, you can monitor your data in near real time and automatically send alert notifications . With an intuitive Kibana interface and a powerful API, it is easy to set up, tune, and monitor your anomaly detectors.

More info: [here](https://github.com/opendistro-for-elasticsearch/anomaly-detection)

### CODE REVIEW

**Comment by axsaucedo** [comment]
@spoilerdo thank you for the contribution - can you add it in alphabetical order?

**Comment by axsaucedo** [comment]
@spoilerdo?

**Comment by spoilerdo** [comment]
Yis sorry i have been veerrry busy with graduation. I will commit next week.

**Comment by spoilerdo** [comment]
@axsaucedo yis I put it in the correct place.

**Comment by axsaucedo** [comment]
Awesome - thank you for the contribution

**Pull request merged**
