### PR TITLE
add pytorch and tensorflow

### PR DESCRIPTION
**Pull request by zhimin-z**
We still need them since they are definitely used in production ML.

### CODE REVIEW

**Review by axsaucedo — CHANGES_REQUESTED** [review]
Thank you for the contribution @zhimin-z 

I've assessed previously whether this list would be adding extensively all tools that are present in production ML but the conclusion always is that the objective I'd not to end up listing absolutely everything such as sklearn and xboost (or tf / PyTorch) just because they are deployed, but the actual relevancein this list would be tfserving and torch serve as those are the actual Frameworks used for production ML. 

So at this stage I would rather not end up just listing absolutely every singe library, otherwise you could also argue that we should also list `python` (for example) given that is present in production as well. This is why I was doubting whether adding these type of libraries, so I would rather focus on frameworks that perform or do productionisation of ML as opposed to Frameworks that are present in prod ML.

**Comment by zhimin-z** [comment]
@axsaucedo I think `python` and tools like `tensorflow` are still different. `tensorflow` is a computation framework in which people can specialize in production-level machine learning. Without adding such tools, our list is always incomplete. Would you mind reconsidering?

**Comment by axsaucedo** [comment]
I do see what you mean, and I agree with your point, the Python point was taking the point to the extreme. I'm just not convinced, and I was already very much in the fence when adding LightGBM, so far my feeling is that these should be removed - these are too much of general application tools which and are so core to modelling and experimentation. 

They indeed are present in experimentation as those are the tools that are productionised, but I fail to see how listing these tools which are much more relevant for modelling and experimentaiton in a production ML list which is focused on higlighting tools relevant for the productionisation of ML

I am not convinced on the value of adding these. Anyone visiting this list I highly doubt they will not have heard of Tensorflow or Pytorch, and referencing these tools would not give them (in my opinion) any further tooling to productionise these.

This is why I am keen on adding tools in the PyTorhc ecosysetm (like torchserve, or even ONNX) which focus on productionisation instead.

I am certainly open for further points, but so far I don't think the points made so far would be big enough to actually add these. Let me know your thoughts.

**Comment by zhimin-z** [comment]
> 
I know what you mean by far. The ultimate reason is that we need to make our list complete in terms of production tools for ML. For example, JAX is coming up as an alternative to TensorFlow, however, we still list it in our list as a production tool (and it is used in the production environment). Of course, our main focus is always general tools that help with the deployment of ML algorithms, but it is still a good point to keep them complete in our list. The added-back tools would not be too many, just to keep the list complete in terms of production-level ML. @axsaucedo

**Comment by axsaucedo** [comment]
> We do not need to add every library for each of them. The added-back tools would not be too many

There are a lot unfortunately... I don't think at this stage I can see how to stop just adding all of them, and saying no to other contributors that want to add yet another non-production but still experimentation/modelling tool.

If we can think of a heuristic that allows us to be quite specific of what tools go in and when to say no, then happy to explore further, but as mentioned I don't really see how we'll be able to find guidelines that don't just open the flood gates to all the modelling and experimentation frameworks.

**Comment by zhimin-z** [comment]
> > We do not need to add every library for each of them. The added-back tools would not be too many
> 
> There are a lot unfortunately... I don't think at this stage I can see how to stop just adding all of them, and saying no to other contributors that want to add yet another non-production but still experimentation/modelling tool.
> 
> If we can think of a heuristic that allows us to be quite specific of what tools go in and when to say no, then happy to explore further, but as mentioned I don't really see how we'll be able to find guidelines that don't just open the flood gates to all the modelling and experimentation frameworks.

Currently, modeling tools are maturing, featuring Tensorflow, Pytorch, Scikit-learn, and their derivatives (like JAX). The tool number won't flood as we can see. If we exclude these tools, our lists seem eventually incomplete in terms of the machine learning computation optimization domain. @axsaucedo

**Comment by axsaucedo** [comment]
> our lists seem eventually incomplete in terms of the machine learning computation optimization domain
I'm not sure I follow - I don't see how not including standard and ubiquitous ML libraries results in being incomplete

I highly doubt people coming across this list would not have heard about Tensorflow, Pytorch, Scikit-learn.

This doesn't seem to address the main issues of having guidelines and heuristics that would specify which of these would be included and which ones wouldn't

If we can come with these then this can be explored but at this stage the argument can be made that other libraries that are also arguably equally important, but I'm not sure what value it would add to include sklearn, tensorflow and pytorch as opposed to focusing in tehir respective ecosystems.

At this stage I would focus on the latter, if we can find a more compelling reason that addresses the points above, then we could explore further but at this stage it seems we're discussing on opinions...

Let's park this for now and if there are some points that you think that could make the case then we can explore further.

**Comment by zhimin-z** [comment]
> > our lists seem eventually incomplete in terms of the machine learning computation optimization domain
> > I'm not sure I follow - I don't see how not including standard and ubiquitous ML libraries results in being incomplete
> 
> I highly doubt people coming across this list would not have heard about Tensorflow, Pytorch, Scikit-learn.
> 
> This doesn't seem to address the main issues of having guidelines and heuristics that would specify which of these would be included and which ones wouldn't
> 
> If we can come with these then this can be explored but at this stage the argument can be made that other libraries that are also arguably equally important, but I'm not sure what value it would add to include sklearn, tensorflow and pytorch as opposed to focusing in tehir respective ecosystems.
> 
> At this stage I would focus on the latter, if we can find a more compelling reason that addresses the points above, then we could explore further but at this stage it seems we're discussing on opinions...
> 
> Let's park this for now and if there are some points that you think that could make the case then we can explore further.
> 
> As always I very much appreciate the efforts @zhimin-z , keen to continue the discussions on these and other active topics

Thanks for your reply, but why not keep this PR open since we can discuss such things easily? I found it very hard to track closed PR when the dicussion still continue. @axsaucedo

**Comment by axsaucedo** [comment]
As discussed in various PRs it's not good practice to keep PRs open just for discussion, this is the point for github issues, as suggested we should open an issue for each of the discussions and continue the discussion there. Thank you @zhimin-z

**Comment by zhimin-z** [comment]
> e discussion there. T

@axsaucedo I know what you mean. But the real challenge is .... when the issue is closed, then it is hard for keep track of them. We indeed need one issue for each discussion but we also need to keep them only when the dispute is not ended. Sometimes I am still discussing but next time I saw the issue is closed then I find it very challenging to keep track of them...TT

**Pull request closed without merging**
