### PR TITLE
Standardize the titles and contents

### PR DESCRIPTION
**Pull request by zhimin-z**
This PR completes the following:

- Standardize the title of each module:
>- Capitalize the title of each module: previously, some titles remained capitalized while others are not.
>- Remove all explicit words related to "framework" since all the tools are regarded as frameworks somehow: previously some titles use "framework", some titles used "libraries", and some titles used none.
>- Use only "&" in the quick link list: previously, some cells used "&" while others used "and"
>- Unify the header line break to two: before, sometimes one, sometimes two
>- Unify the "s" plural forms into singular forms: before, some titles use plural forms while some are not
>- Unify the module title name with the quick link cell name (except the first one since the name is too long for a cell)
>- Change "Data Pipeline & ETL" into "Data Pipeline" for two reasons: 1) ETL pipeline is a synonym of data pipeline classically 2) Recently, there exist other variants such as [ELT pipeline](https://www.talend.com/resources/elt-vs-etl/) using the same set of tools; thus the scope of ETL pipeline is narrow in modern data science. 

- Standardize the content of each module:
>- Add missing periods for tool description
>- Standardize links by using open-source repo only (only if it is an open-source project)
>- Standardize external links in the description (e.g. video/demo/article/paper)
>- Standardize tool names (e.g. replace Kafka Streams with Apache Kafka, Guild AI)
>- Add a star badge for those that miss
>- Update the repo link with the latest (e.g. Stable Baselines has the latest repo called baseline3 detached with its original fork project)
>- Remove duplicate projects (e.g. Redis-ML is replaced by Redis-AI, which always shows up in the list)
>- Remove non-existent projects (e.g. Hydrogen)
>- Remove integrated projects (e.g.Wav2Letter++ is integrated into Flashlight)
>- Remove tricks rather than tools (e.g. "XKCD-style plots" is a plotting style in Matplotlib)
>- Add new ML libraries (e.g. Flashlight is an ML platform released by Meta AI)
>- Move misclassified tools to the right place (e.g. PredictionIO is a model serving tool rather than a model versioning one)
>- Remove pure research projects that do not aim to productionize machine learning (e.g. https://github.com/taolei87/rcnn)
>- Extend descriptions for some tools (e.g. BigML, D2iQ Kaptain)

### CODE REVIEW

**Comment by zhimin-z** [comment]
Take a look at the markdown after standardizing, it looks much neatier!

**Review by axsaucedo — APPROVED** [review]
This is better indeed, thank you for taking the time to clean up the resource

**Comment by axsaucedo** [comment]
There seem to be some merge conflicts so we can merge once resolved

**Comment by zhimin-z** [comment]
Conflicts solved!

**Review by axsaucedo — APPROVED** [review]
Thank you for the contribution @zhimin-z

**Pull request merged**
