### PR TITLE
Add data manipulation module and tools

### PR DESCRIPTION
**Pull request by zhimin-z**
This PR aims to add a new module named "Dataset management" (or dataset exploration/manipulation/profiling, or whatever concerns the inspection & generation & transformation of a dataset) as well as one of the tools.

### CODE REVIEW

**Comment by axsaucedo** [comment]
Snorkel falls on data labelling, not sure if adding a new section on dataset management as we already have "metadata management", whcih encompasses this, I woudl rather keep the metadata management unless there is a more specific word, but this goes beyond just datasets and encompasses also metadata of models, ml services, and training data , etc

**Comment by zhimin-z** [comment]
> Snorkel falls on data labelling, not sure if adding a new section on dataset management as we already have "metadata management", whcih encompasses this, I woudl rather keep the metadata management unless there is a more specific word, but this goes beyond just datasets and encompasses also metadata of models, ml services, and training data , etc

I do not see a place for Kangas on the current list. where can we put it?

**Comment by axsaucedo** [comment]
I would say on the metadata management section, it could extend to data metadata

**Comment by zhimin-z** [comment]
> I would say on the metadata management section, it could extend to data metadata

Well, unlike the metadata management tool like [Apache Atlas](https://github.com/apache/atlas), [Kangas](https://github.com/comet-ml/kangas) is a dataset exploration tool, if you take a look look at its documentation.

**Comment by zhimin-z** [comment]
> I would say on the metadata management section, it could extend to data metadata

Hi @axsaucedo Would you mind reopening this in case for further discussion? Appreciated a lot!

**Pull request closed without merging**
