### PR TITLE
Add Diffgram

### PR DESCRIPTION
**Pull request by swirlingsand**
-> Open SDK in tools section
-> Commercial side in commercial section
Hopefully put in right spot! :)

### CODE REVIEW

**Comment by axsaucedo** [comment]
The diffgram OSS seems to be just an SDK - the list is for OSS frameworks so won't be adding this one unfortunately. But it would still be a good addition to the commercial list, if you remove emoji and add further details we could add it

**Review by axsaucedo — CHANGES_REQUESTED** [review]
The diffgram OSS seems to be just an SDK - the list is for OSS frameworks so won't be adding this one unfortunately. But it would still be a good addition to the commercial list, if you remove emoji and add further details we could add it

**Comment by swirlingsand** [comment]
@axsaucedo Is this good to go now? 👍

**Comment by axsaucedo** [comment]
Looks good @swirlingsand , if you can add a more descriptive sentence should be good to merge 👍

**Comment by swirlingsand** [comment]
@axsaucedo Updated!

**Comment by axsaucedo** [comment]
NIce one!

**Pull request merged**
