### PR TITLE
Added Nuclio and Iguazio

### PR DESCRIPTION
**Pull request by gilad-shaham**

### CODE REVIEW

**Comment by axsaucedo** [comment]
Thank you for the great contribution @gilad-shaham! All looks good, although looking at MLRun it seems it's a CLI/SDK wrapper to kubeflow pipelines and nuclio, so not sure I would include it as part of training or serving. Other than that looks good so if you can remove we can merge. Thanks!

**Comment by gilad-shaham** [comment]
Thanks @axsaucedo 
MLRun is actually more than CLI/SDK wrapper as it has its own assets. At its core it's an open source end-to-end automation, it does leverage Kubeflow and Nuclio so it doesn't reinvent the wheel, but it makes it by far easier to deploy those pipelines and integrate. Furthermore, it makes it easier to work with multiple runtimes so the user doesn't have to change their code.
See https://github.com/mlrun/demos for some examples and the open source function marketplace https://github.com/mlrun/functions/tree/development for more information on what it does.
Perhaps the description doesn't do it justice :)

I can remove from the PR if you insist, but I think it fits the bill, and I haven't seen similar projects out there (certainly not open source)

**Comment by axsaucedo** [comment]
@gilad-shaham thank you for the links, I did have a look, I think for now we can remove it and we can explore adding it in the future if there is a more specific section is added as there may be other projects that I have begin to see adding abstractions on top of serving / training pipeline frameworks

**Comment by gilad-shaham** [comment]
@axsaucedo updated as per your request

**Comment by axsaucedo** [comment]
Looks great @gilad-shaham

**Pull request merged**
