### PR TITLE
Experiment Tracking

### PR DESCRIPTION
**Pull request by zhimin-z**
This PR aims for the following:
1. Tweak the module name from "model/data versioning" to "_experiment tracking_" (**or** we can use "_asset management_" directly and merge the _metadata management_ module together)  considering the nature of the list of tools under this module. 
- These tools, after all, aim for reproducible ML models which can be later deployed in real-life cases. Also, these tools not only track the trained models as well as the fed dataset, but also the artifacts (e.g. generated images/text, ML pipeline scripts, hyperparameters, performance metrics, reports, and logs, etc) during a typical ML model lifecycle. 
- The current name "Model & Data Versioning" seems far from enough to conclude these tools on our list. My idea is also supported by Table 2 of [a recently accepted paper](https://dl.acm.org/doi/10.1145/3543847) in ACM Comput Surv, but I am open to any further discussion.
- 
image
2. Add a research experiment tracking tool to "experiment tracking"

### CODE REVIEW

**Comment by axsaucedo** [comment]
I'm not sure about the name of Experiment tracking for model & data versioning - namely as experiment tracking does not encompass data versioning, I am keen to add the tool and perhaps if you can provide a bit more explanation of this point

**Comment by zhimin-z** [comment]
These tools, as written in the aforementioned [paper](https://dl.acm.org/doi/10.1145/3543847), are designed for tracking experiment tracking purposes. Experiment tracking indeed covers models, datasets, execution data, metrics, hyperparameters, and generated artifacts according to the major idea in the [paper](https://dl.acm.org/doi/10.1145/3543847) as well.

**Comment by zhimin-z** [comment]
> I'm not sure about the name of Experiment tracking for model & data versioning - namely as experiment tracking does not encompass data versioning, I am keen to add the tool and perhaps if you can provide a bit more explanation of this point

Would you mind reopening this pr for further discussion? @axsaucedo

**Comment by zhimin-z** [comment]
> I'm not sure about the name of Experiment tracking for model & data versioning - namely as experiment tracking does not encompass data versioning, I am keen to add the tool and perhaps if you can provide a bit more explanation of this point

Hi @axsaucedo Would you mind reopening this in case for further discussion? Appreciated a lot!

**Pull request closed without merging**
